
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/home/vboxuser/Schreibtisch/Tracker-Schulweg-SoftwareEngineering-Projekt/GUI/assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1920x1080")
window.configure(bg = "#353333")


canvas = Canvas(
    window,
    bg = "#353333",
    height = 1080,
    width = 1920,
    bd = 2,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)

karte_image = PhotoImage(
    file=relative_to_assets("karte.png"))
karte = canvas.create_image(
    640.0,
    540.0,
    image=karte_image
)

routen_image = PhotoImage(
    file=relative_to_assets("routen.png"))
routen = Button(
    image=routen_image,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("routen clicked"), #nichts tun?
    relief="flat"
)
routen.place(
    x=1280.0,
    y=0.0,
    width=640.0,
    height=216.0
)

ausschalten_image = PhotoImage(
    file=relative_to_assets("ausschalten.png"))
ausschalten = Button(
    image=ausschalten_image,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("ausschalten clicked"), #ausschalten funktion aufrufen
    relief="flat"
)
ausschalten.place(
    x=51.0,
    y=929.0,
    width=100.0,
    height=100.0
)

canvas.create_rectangle(
    1278.0,
    0.0,
    1919.0,
    1079.0,
    fill="#353333",
    outline="#FFFFFF")

ausklappen_image = PhotoImage(
    file=relative_to_assets("ausklappen.png"))
ausklappen = Button(
    image=ausklappen_image,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("ausklappen clicked"), #aufrufen routen_menü
    relief="flat"
)
ausklappen.place(
    x=1071.0,
    y=0.0,
    width=218.0,
    height=218.0
)

canvas.create_rectangle(
    1282.0,
    218.0,
    1918.0,
    773.0,
    fill="#000000",
    outline="")

routen_löschen_image = PhotoImage(
    file=relative_to_assets("routen_löschen.png"))
routen_löschen = Button(
    image=routen_löschen_image,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("routen löschen clicked"), #einzelne route löschen, alle routen löschen?
    relief="flat"
)
routen_löschen.place(
    x=1459.0,
    y=782.0,
    width=280.0,
    height=97.67442321777344
)

zurück_image = PhotoImage(
    file=relative_to_assets("zurück.png"))
zurück = Button(
    image=zurück_image,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("zurück clicked"), #aufruf routen_menü
    relief="flat"
)
zurück.place(
    x=1459.0,
    y=930.0,
    width=280.0,
    height=97.67442321777344
)
window.resizable(False, False)
window.mainloop()
